### ISSUE TITLE
RectPack not packing properly

### ISSUE THREAD

**Issue by m9dfukc** [microdee/mp.essentials#1]
Hi,

it seems that (booth) Rect packing nodes  don't pack properly.

![example](https://user-images.githubusercontent.com/551597/30364042-d1ada236-9862-11e7-8dbe-dfff9e6e4985.png)

[packing_test.v4p.zip](https://github.com/microdee/mp.essentials/files/1298517/packing_test.v4p.zip)

edit: ignore the image duplicates, they are in the source material. Actually I am talking about the packaging and the space in between.

**Comment by microdee** [comment]
I need to create a help patch there, the pivot points of the rectangles are
not in center but in the top left corner (or on transform 2D center: - 0.5,
0.5

**Comment by m9dfukc** [comment]
Looks better now ;)


[RectPack (help).v4p.zip](https://github.com/microdee/mp.essentials/files/1298662/RectPack.help.v4p.zip)
